services:
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes: 
      - ./curriculum/laravel:/var/laravel-curriculum
    depends_on:
      - mysql
  nginx:
    image: nginx:1.23
    ports:
      - 8080:80
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./curriculum/laravel:/var/laravel-curriculum
    depends_on:
      - app
  mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql:/var/lib/mysql
      - ./curriculum/sql:/var/sql-curriculum/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    restart: always
